IMAGE   ?= barchart-candles
SERVICE ?= barchart
REDIS   ?= redis
PORT    ?= 8000

.PHONY: help run install install-dev test build up down restart logs shell ps migrate migration redis-up redis-cli flush clean

help:
	@awk 'BEGIN{FS=":.*##"} /^[a-zA-Z_-]+:.*##/ {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

run: ## Run the server locally (expects a reachable Redis; see redis-up)
	HOST=127.0.0.1 PORT=$(PORT) uvicorn app.main:app --host 127.0.0.1 --port $(PORT) --reload

install: ## Install Python deps into the active environment
	pip install -r requirements.txt

install-dev: ## Install test/dev deps (pytest, etc.)
	pip install -r requirements-dev.txt

test: ## Run the test suite (requires docker compose stack running)
	pytest

build: ## Build the Docker image
	docker compose build

up: ## Start app + redis in the background
	docker compose up -d --build
	@echo "→ http://localhost:$(PORT)"

down: ## Stop and remove containers
	docker compose down

restart: down up ## Restart containers

logs: ## Tail app logs
	docker compose logs -f --tail=100 $(SERVICE)

shell: ## Open a shell in the running app container
	docker compose exec $(SERVICE) sh

ps: ## Show container status
	docker compose ps

migrate: ## Apply pending DB migrations
	docker compose exec $(SERVICE) alembic upgrade head

migration: ## Generate a new autogenerated migration (usage: make migration name="add foo")
	docker compose exec $(SERVICE) alembic revision --autogenerate -m "$(name)"

redis-up: ## Start just the redis container (for local `make run`)
	docker compose up -d $(REDIS)

redis-cli: ## Open redis-cli in the redis container
	docker compose exec $(REDIS) redis-cli

flush: ## Flush the cache (FLUSHDB)
	docker compose exec $(REDIS) redis-cli FLUSHDB

clean: ## Remove containers and local images
	-docker compose down --rmi local --remove-orphans
